In [ ]:
#Mithun G : 1BM22CS096
import numpy as np
from collections import deque

class Node:
    def __init__(self, state, parent, action):
        self.state = state  
        self.parent = parent 
        self.action = action 

class Puzzle:
    def __init__(self, start, start_index, goal, goal_index):
        self.start = [start, start_index] 
        self.goal = [goal, goal_index] 
        self.solution = None

    def neighbors(self, state):
        mat, (row, col) = state  
        results = []

        if row > 0:
            mat1 = np.copy(mat)
            mat1[row][col] = mat1[row - 1][col]
            mat1[row - 1][col] = 0
            results.append(('up', [mat1, (row - 1, col)]))

        if col > 0:
            mat1 = np.copy(mat)
            mat1[row][col] = mat1[row][col - 1]
            mat1[row][col - 1] = 0
            results.append(('left', [mat1, (row, col - 1)]))

        if row < 2:
            mat1 = np.copy(mat)
            mat1[row][col] = mat1[row + 1][col]
            mat1[row + 1][col] = 0
            results.append(('down', [mat1, (row + 1, col)]))

        if col < 2:
            mat1 = np.copy(mat)
            mat1[row][col] = mat1[row][col + 1]
            mat1[row][col + 1] = 0
            results.append(('right', [mat1, (row, col + 1)]))

        return results

    def solve_bfs(self):
        start = Node(state=self.start, parent=None, action=None)
        frontier = deque([start]) 
        explored = []  

        while frontier:
            node = frontier.popleft()

            if (node.state[0] == self.goal[0]).all():
                actions = []
                cells = []
                while node.parent is not None:
                    actions.append(node.action)
                    cells.append(node.state)
                    node = node.parent
                actions.reverse()
                cells.reverse()
                self.solution = (actions, cells)
                return self.solution

            explored.append(node.state)

            for action, neighbor in self.neighbors(node.state):
                if not any((explored_state[0] == neighbor[0]).all() for explored_state in explored):
                    if not any((frontier_node.state[0] == neighbor[0]).all() for frontier_node in frontier):
                        child_node = Node(state=neighbor, parent=node, action=action)
                        frontier.append(child_node)

        raise Exception("No solution found.")

    def print_solution(self):
        if self.solution is None:
            print("No solution available.")
            return

        print("Initial State:")
        print(self.start[0], "\n")

        for action, state in zip(self.solution[0], self.solution[1]):
            print(f"Action: {action}")
            print(state[0], "\n")

        print("Goal Reached!")


def get_puzzle_input():
    print("Enter the 8-puzzle configuration (use 0 for the blank space):")
    puzzle = []
    for i in range(3):
        row = input(f"Enter row {i + 1} (space-separated numbers): ").split()
        puzzle.append([int(num) for num in row])
    return np.array(puzzle)

start = get_puzzle_input()
goal = get_puzzle_input()

start_index = (np.where(start == 0)[0][0], np.where(start == 0)[1][0])
goal_index = (np.where(goal == 0)[0][0], np.where(goal == 0)[1][0])

puzzle = Puzzle(start, start_index, goal, goal_index)

puzzle.solve_bfs()

puzzle.print_solution()

Enter the 8-puzzle configuration (use 0 for the blank space):


Enter row 1 (space-separated numbers):  1 2 3
Enter row 2 (space-separated numbers):  4 5 6
Enter row 3 (space-separated numbers):  7 8 0


Enter the 8-puzzle configuration (use 0 for the blank space):


Enter row 1 (space-separated numbers):  1 2 3
Enter row 2 (space-separated numbers):  0 4 5
Enter row 3 (space-separated numbers):  7 8 6


Initial State:
[[1 2 3]
 [4 5 6]
 [7 8 0]] 

Action: up
[[1 2 3]
 [4 5 0]
 [7 8 6]] 

Action: left
[[1 2 3]
 [4 0 5]
 [7 8 6]] 

Action: left
[[1 2 3]
 [0 4 5]
 [7 8 6]] 

Goal Reached!
